[package]
name = "agent-amm"
version = "0.1.0"
description = "Agent Mesh AMM"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "agent_amm"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "0.32.1"
anchor-spl = { version = "0.32.1", features = ["default"] }
